### ISSUE TITLE
app.js refers to obsolete 'group' attribute on EdgeGrid

### ISSUE THREAD

**Issue by damarshall** [akamai-open/papi-demo-app#3]
Suggested one-line patch (to get working with latest EdgeGrid):

`$ git diff
diff --git a/app.js b/app.js
index 235eedd..4395ca0 100644
--- a/app.js
+++ b/app.js
@@ -22,7 +22,7 @@ var bodyParser = require('body-parser');
 var EdgeGrid =require('edgegrid');
 var eg = new EdgeGrid({
   path: __dirname + '/.edgerc',
-  group: 'papi'
-  section: 'papi'
  });
  var routes = require('./routes/index');
  var getGroups = require('./routes/groups');
  warning: LF will be replaced by CRLF in public/js/toArrayFilter.js.
  The file will have its original line endings in your working directory.`

**Comment by damarshall** [comment]
on patch above, that should be: "- group: 'papi'  + section: 'papi'"

**Comment by ktyacke** [comment]
Hey @damarshall would you ming submitting a PR for this fix? Thanks for catching this!

**Comment by damarshall** [comment]
PR submitted
